/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes.view;

import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        BTNHOME = new javax.swing.JButton();
        BTNPAKET = new javax.swing.JButton();
        BTNPENGIRIM = new javax.swing.JButton();
        BTNPENERIMA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNLOGOUT = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        PAKETPANEL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        PENGIRIMPANEL = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PENERIMAPANEL = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        HOMEPANEL = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TUBES");

        bodyPanel.setBackground(new java.awt.Color(52, 73, 94));

        menuPanel.setBackground(new java.awt.Color(52, 73, 94));
        menuPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));

        BTNHOME.setBackground(new java.awt.Color(52, 73, 94));
        BTNHOME.setFont(new java.awt.Font("Swis721 Blk BT", 1, 13)); // NOI18N
        BTNHOME.setForeground(new java.awt.Color(52, 73, 94));
        BTNHOME.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-home-64.png")); // NOI18N
        BTNHOME.setText("HOME");
        BTNHOME.setToolTipText("");
        BTNHOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHOMEActionPerformed(evt);
            }
        });

        BTNPAKET.setBackground(new java.awt.Color(52, 73, 94));
        BTNPAKET.setFont(new java.awt.Font("Swis721 Blk BT", 1, 13)); // NOI18N
        BTNPAKET.setForeground(new java.awt.Color(52, 73, 94));
        BTNPAKET.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-box-64.png")); // NOI18N
        BTNPAKET.setText("PAKET");
        BTNPAKET.setToolTipText("");
        BTNPAKET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPAKETActionPerformed(evt);
            }
        });

        BTNPENGIRIM.setBackground(new java.awt.Color(52, 73, 94));
        BTNPENGIRIM.setFont(new java.awt.Font("Swis721 Blk BT", 1, 13)); // NOI18N
        BTNPENGIRIM.setForeground(new java.awt.Color(52, 73, 94));
        BTNPENGIRIM.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-human-research-program-30.png")); // NOI18N
        BTNPENGIRIM.setText("PENGIRIM");
        BTNPENGIRIM.setToolTipText("");
        BTNPENGIRIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPENGIRIMActionPerformed(evt);
            }
        });

        BTNPENERIMA.setBackground(new java.awt.Color(52, 73, 94));
        BTNPENERIMA.setFont(new java.awt.Font("Swis721 Blk BT", 1, 13)); // NOI18N
        BTNPENERIMA.setForeground(new java.awt.Color(52, 73, 94));
        BTNPENERIMA.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-google-web-search-48.png")); // NOI18N
        BTNPENERIMA.setText("PENERIMA");
        BTNPENERIMA.setToolTipText("");
        BTNPENERIMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNPENERIMAActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-paper-plane-96.png")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Magneto", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JPB");

        BTNLOGOUT.setFont(new java.awt.Font("Swis721 BlkCn BT", 1, 18)); // NOI18N
        BTNLOGOUT.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Downloads\\icons8-hand-64.png")); // NOI18N
        BTNLOGOUT.setText("LOGOUT");
        BTNLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLOGOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(menuPanelLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNPENERIMA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNPENGIRIM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNPAKET, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNHOME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BTNLOGOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(BTNHOME, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNPAKET, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNPENGIRIM, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNPENERIMA, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNLOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(52, 73, 94));
        MainPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.lightGray));
        MainPanel.setLayout(new java.awt.CardLayout());

        PAKETPANEL.setBackground(new java.awt.Color(49, 165, 166));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("DATA PAKET");

        javax.swing.GroupLayout PAKETPANELLayout = new javax.swing.GroupLayout(PAKETPANEL);
        PAKETPANEL.setLayout(PAKETPANELLayout);
        PAKETPANELLayout.setHorizontalGroup(
            PAKETPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAKETPANELLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(760, Short.MAX_VALUE))
        );
        PAKETPANELLayout.setVerticalGroup(
            PAKETPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PAKETPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(536, Short.MAX_VALUE))
        );

        MainPanel.add(PAKETPANEL, "card3");

        PENGIRIMPANEL.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DATA PENGIRIM");
        jLabel5.setToolTipText("");

        javax.swing.GroupLayout PENGIRIMPANELLayout = new javax.swing.GroupLayout(PENGIRIMPANEL);
        PENGIRIMPANEL.setLayout(PENGIRIMPANELLayout);
        PENGIRIMPANELLayout.setHorizontalGroup(
            PENGIRIMPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PENGIRIMPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(715, Short.MAX_VALUE))
        );
        PENGIRIMPANELLayout.setVerticalGroup(
            PENGIRIMPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PENGIRIMPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(542, Short.MAX_VALUE))
        );

        MainPanel.add(PENGIRIMPANEL, "card4");

        PENERIMAPANEL.setBackground(new java.awt.Color(127, 140, 141));

        jLabel6.setFont(new java.awt.Font("Square721 Cn BT", 1, 24)); // NOI18N
        jLabel6.setText("DATA PENERIMA");

        javax.swing.GroupLayout PENERIMAPANELLayout = new javax.swing.GroupLayout(PENERIMAPANEL);
        PENERIMAPANEL.setLayout(PENERIMAPANELLayout);
        PENERIMAPANELLayout.setHorizontalGroup(
            PENERIMAPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PENERIMAPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        PENERIMAPANELLayout.setVerticalGroup(
            PENERIMAPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PENERIMAPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(546, Short.MAX_VALUE))
        );

        MainPanel.add(PENERIMAPANEL, "card5");

        HOMEPANEL.setBackground(new java.awt.Color(52, 73, 94));

        jLabel3.setFont(new java.awt.Font("Minion Pro Cond", 1, 24)); // NOI18N
        jLabel3.setText("WELCOME");

        javax.swing.GroupLayout HOMEPANELLayout = new javax.swing.GroupLayout(HOMEPANEL);
        HOMEPANEL.setLayout(HOMEPANELLayout);
        HOMEPANELLayout.setHorizontalGroup(
            HOMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPANELLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(679, Short.MAX_VALUE))
        );
        HOMEPANELLayout.setVerticalGroup(
            HOMEPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HOMEPANELLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(526, Short.MAX_VALUE))
        );

        MainPanel.add(HOMEPANEL, "card2");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BTNHOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHOMEActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll ();
        MainPanel.repaint();
        
        MainPanel.add(HOMEPANEL);
        MainPanel.repaint();
        MainPanel.revalidate();
        
    }//GEN-LAST:event_BTNHOMEActionPerformed

    private void BTNPAKETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPAKETActionPerformed
        // TODO add your handling code here:
         MainPanel.removeAll ();
        MainPanel.repaint();
        
        MainPanel.add(PAKETPANEL);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BTNPAKETActionPerformed

    private void BTNPENGIRIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPENGIRIMActionPerformed
        // TODO add your handling code here:
         MainPanel.removeAll ();
        MainPanel.repaint();
        
        MainPanel.add(PENGIRIMPANEL);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BTNPENGIRIMActionPerformed

    private void BTNPENERIMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNPENERIMAActionPerformed
        // TODO add your handling code here:
         MainPanel.removeAll ();
        MainPanel.repaint();
        
        MainPanel.add(PENERIMAPANEL);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_BTNPENERIMAActionPerformed

    private void BTNLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLOGOUTActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,"Apakah Anda Ingin Keluar ","Peringatan" ,dialogBtn);
        
        if (dialogResult == 0 ){
            
            System.exit(0);
        }
        else{
            
        }
        
    }//GEN-LAST:event_BTNLOGOUTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNHOME;
    private javax.swing.JButton BTNLOGOUT;
    private javax.swing.JButton BTNPAKET;
    private javax.swing.JButton BTNPENERIMA;
    private javax.swing.JButton BTNPENGIRIM;
    private javax.swing.JPanel HOMEPANEL;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PAKETPANEL;
    private javax.swing.JPanel PENERIMAPANEL;
    private javax.swing.JPanel PENGIRIMPANEL;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
